---
run:
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - durationcheck
    - forcetypeassert
    - gofmt
    - goimports
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - promlinter
    - structcheck
    - tagliatelle
    - typecheck
    - varcheck
    - wastedassign
    # - asciicheck
    # - bodyclose
    # - cyclop
    # - dogsled
    # - dupl
    # - errcheck
    # - errorlint
    # - exhaustive
    # - exhaustivestruct
    # - exportloopref
    # - forbidigo
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    # - gofumpt
    # - goheader
    # - golint
    # - gomnd
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - ifshort
    # - lll
    # - nestif
    # - nlreturn
    # - noctx
    # - nolintlint
    # - paralleltest
    # - revive
    # - rowserrcheck
    # - scopelint
    # - sqlclosecheck
    # - staticcheck
    # - stylecheck
    # - testpackage
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - unused
    # - whitespace
    # - wrapcheck
    # - wsl
linters-settings:
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - nilValReturn
      - offBy1
      - sloppyReassign
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock
