name: cri-tools e2e test
on: [push, pull_request]
jobs:
  test-e2e:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Cache go modules and build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            '%LocalAppData%\go-build' # Windows
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/kubernetes-sigs/cri-tools

      - name: Cache go modules and build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            '%LocalAppData%\go-build' # Windows
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run e2e test
        run: |
          sudo apt-get update &&\
          sudo apt-get install -y libseccomp-dev

          VERSION=v0.8.6 &&\
          sudo mkdir -p /opt/cni/bin &&\
          sudo wget -qO- https://github.com/containernetworking/plugins/releases/download/$VERSION/cni-plugins-linux-amd64-$VERSION.tgz \
              | sudo tar xfz - -C /opt/cni/bin &&\
          ls -lah /opt/cni/bin

          VERSION=v1.0.0-rc92 &&\
          sudo wget -q -O \
            /usr/bin/runc \
            https://github.com/opencontainers/runc/releases/download/$VERSION/runc.amd64 &&\
          sudo chmod +x /usr/bin/runc &&\
          runc --version

          sudo -E PATH=$PATH make all install test-e2e TESTFLAGS=-v
        working-directory: src/github.com/kubernetes-sigs/cri-tools
